<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Xapp_Xapp' => array($vendorDir),
    'Xapp_Rpc' => array($vendorDir),
    'Xapp_Orm' => array($vendorDir),
    'Xapp_Log' => array($vendorDir),
    'Xapp_Cache' => array($vendorDir),
);
