<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    $vendorDir . '/composer/firephp/firephp-core/lib/FirePHPCore/fb.php',
);
